# Generated by Django 4.1.3 on 2023-06-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobFunction', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobIndustries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobIndustries', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobLocation', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('scraped_date', models.CharField(max_length=1000)),
                ('job_link', models.URLField(max_length=5000)),
                ('Job_Function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Functions', to='scraper.jobfunctions')),
                ('Job_Industries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Locations', to='scraper.jobindustries')),
                ('Job_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Location', to='scraper.joblocation')),
            ],
        ),
    ]
