# Generated by Django 4.1.3 on 2023-06-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('scraped_date', models.CharField(max_length=1000)),
                ('job_link', models.URLField(max_length=5000)),
            ],
        ),
    ]
