# Generated by Django 4.1.3 on 2023-06-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfunctions',
            name='jobFunction',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Job_Function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Functions', to='scraper.jobfunctions'),
        ),
    ]
