# Generated by Django 4.1.3 on 2023-06-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Job_Industries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Industries', to='scraper.jobindustries'),
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=20000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='scraper.jobs')),
            ],
        ),
    ]
