# Generated by Django 4.1.3 on 2023-06-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_jobs_job_industries_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Job_details',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
