# Generated by Django 4.1.3 on 2023-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_jbdate_job_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jbdate',
            name='job_link',
            field=models.URLField(default='', max_length=5000),
        ),
    ]
