# Generated by Django 4.1.3 on 2023-06-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_jobs_job_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Job_details',
            new_name='Job_Details',
        ),
    ]
