# Generated by Django 4.1.3 on 2023-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_jbdate_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbdate',
            name='job_employer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
