# Generated by Django 4.1.3 on 2023-06-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_jbdate_job_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jbdate',
            name='job_employer',
        ),
    ]
