# Generated by Django 4.1.3 on 2023-06-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_rename_job_details_jobs_job_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='bold',
            field=models.BooleanField(default=False),
        ),
    ]
