# Generated by Django 4.1.3 on 2023-06-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_remove_jbdate_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbdate',
            name='job_function',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
